name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify your Node.js version

    - name: Install dependencies
      run: |
        cd client # Change to client directory
        npm install

    - name: Build client
      run: |
        cd client # Change to client directory
        npm run build # Run your build command

    - name: Run tests
      run: |
        cd client # Change to client directory
        npm test

    - name: Deploy to Vercel
      run: |
        cd client # Change to client directory
        npm install -g vercel # Install Vercel CLI
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }} # Deploy to Vercel
